name: holding_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_svg: ^0.22.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
#    - assets/icons/menu/
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope_Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope_Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope_Bold.ttf
          weight: 700
