import 'package:flutter/cupertino.dart';

class AppTheme {
  static const Color black = Color(0xFF000000);
  static const Color rectAngelOne = Color(0xFFFEF6E1);
  static const Color rectAngelTwo = Color(0xFFE3F3FF);
  static const Color rectAngelThree = Color(0xFFDDFFDA);
  static const Color holding3Text = Color(0xFF00B6E4);
  static const Color holding1 = Color(0xFFFFFCE3);
  static const Color holding2 = Color(0xFFE9FFE3);
  static const Color holding3 = Color(0xFFE3E6FF);
  static const Color holdingOne = Color(0xFFFFF9C6);
  static const Color holdingTwo = Color(0xFFC6FFDD);
  static const Color holdingThree = Color(0xFFC7C6FF);
  static const Color holdingCircle = Color(0xFFCBD0FF);
  static const Color neturalGreen = Color(0xFFDDFFDA);
  static const Color magentaBlue = Color(0xFFE3F3FF);
  static const Color lightYellow = Color(0xFFFEF6E1);
  static const Color yellow = Color(0xFFFFC029);
  static const Color yellowCircle = Color(0xFFFFE851);
  static const Color lightGreen = Color(0xFF49CD22);
  static const Color circleGreen = Color(0xFF8CFE6D);
  static const Color backGray = Color(0xFFE5E5E5);
  static const Color white = Color(0xFFFFFFFF);
  static const Color neturalBlue = Color(0xFF354B91);
  static const Color neturalDark = Color(0xFF354B91);
  static const Color lightgray = Color(0xFFC4C4C4);
  static const Color neturalGray = Color(0xFFE0E0E0);
  static const Color mainlyBLUE = Color(0xFFBCADCA);
  static const Color gray = Color(0xFFB8B8B8);
  static const Color magenta = Color(0xFF595085);
  static const Color magentaDark = Color(0xFF403572);
  static const Color violetDark = Color(0xFF7F288E);
  static const Color levender = Color(0xFFF6F5FB);
  static const Color levenderRed = Color(0xFFFFF4F4);
  static const Color lightRed = Color(0xFFFF5648);
  static const Color red = Color(0xFFDB303F);
  static const Color lightBlue = Color(0xFF5A6CF3);
  static const Color darkGray = Color(0xFF7A7A7A);
}
